name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump Version and Push Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: minor
        WITH_V: true

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag
      id: version
      run: |
        echo "VERSION=${{ needs.bump-version.outputs.new_tag }}" >> $GITHUB_ENV

    - name: Build Docker image with version tag
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-api-test:${VERSION} .

    - name: Push both tags
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fast-api-test:${VERSION}
